// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "Menu Screen":return img`
ffffffffffffffffffffffffcffffffffffffffffffffffffffdddddfffffffffffffddfffffdfdfffffffffffffffffffffffffffffffffffffffffffffffcffcffffffffffffffffffffffffffffff
fffcfffffffffffffffffcfffffffffffffbffbffffffffffffdddddfffffffffffffddfffffffff11fffffffffffffffffff1fffffffff11fffffffffffffffffffffffffffffffcfcfffffffffffff
fffffcffffffffffffffffffffffffffffffffffffffffffffffdddff11fffff11ffffffffffffff11fff11fffffffffffffffff1ffffff11fffffbbfffffffffffffffffffffffffffffcfcffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffff11fffffffffffffffffff11fffff1ff1ffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
ffffbffbfffbfffbfffffffffffffffffffffffffffffffdfdfffffffffffffffffffccfffffccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffbfbfffffffffff
ffffffffffffbfbffffffffffdfffffffffffffffffffffffffffffffffffffffffffccccccfccccccccfffffcccccffffffffccfffffffffff1ffffffbbfffbffffffffffbbfffffffffffffcfcffff
fffffffffffffffffffffffffffdffffdfffffffffffdffffffff1ff1fffffffffffcccccccffccccccccccccccccccfffcccccccfffcfffffffff1fffbbfffbfffbffffffffffffbfbfffffffffffff
ffffffffffffffffffffffdffdffffdffffff11ffffffffffffffffffffffffffffccccccccfccccccccccccccccccccffcccccccfffccccffffffffffffffffffbffffffffffffffffffbfbffffffff
fffffffffffffffffffffffffffffffffffff11ffffdffffffccfffffffcccfffccccccccccccccccccccccccccccccccffcccccccccccccffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffccccccccffcccccffccccccccccccccccccccccccccccccccfcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffff1f1fffffffffffffffffccfffcccccccccccccccfccccccccccccccccccccccccccccccccfcccccccccccccccfffffffffffffffffffffffffff1ffffffffffffffffffc
ffffffffddfffffffffffffffffffff11ffffffffffccffffccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccfffff1ffff1ffffffffffffff11fffffffbfbffffffffc
ffffffffddffffdfdfffffffffffff1111ffffcccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff1ff1ffffffff11ffffffffffffffffffffffffff
fffbbfffffffffffffffffffffffff1111ffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffff11ffffffffff11ffffffffffffff
fffbbfffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccfffffffffffffffffffffffffffff1fffffffffffffff
fffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccffffffccfffff1ffffffffffffffffffffffffbbfffff
ffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccfffccccffffff1fffffff1ffffffffffffffbbfffff
fffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccfffcccccfffffffffffffffffffffffdfffffffffff
ffffffbcccd1dd11d11111111ccdd1d11111cd1d11cc1d111cd1dd11d11ccdd1d11111cd1d11ccd1dd11dd1111111cccbcccccccccccccccccccccfffcccccccffffffffffffff1ffffffffdffffffff
ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddd1cccbccccccccccccccccccccccffcccccccccccffcfffffffffffffffffffffffff
ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbccccccccccccccccccccccffccccccccccccfccffffffffffffffffffffffff
ffffffbcccdddddddddddddd1bbdddddddddbdddd1bbdddd1bdddddddd1bbdddddddddbdddd1bbdddddddddddddd1cccbccccccccccccccccccccccccfccccccccccccccffffffffffffffffffffffff
cfffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbcccccccccccccccccccccccccccccccccccccccccfff11fffffffffffffffff
ffcfffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbbbbbbbbbbccccbcccccccccccccccccccccccccccccccccccccccccccf11fffffffffffffffff
ffffffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbb1d111bbbbccccbcccccccccccccccccccccccccccccccccccccccccccffffffffff111fffffff
fffff1bcccdddddb1d11dddddbbdddddbbbbbdddd1bbdddd1b1d11dddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccffffffffff11111ffffff
ffffffbcccdddddbdddddddd1bbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffff
ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffbf
ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccffffffcfffffff111fffffff
ffffffbcccdddddbbbbbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccfffffcccffffffffffffffbf
ffffffbcccdddddbd1d111bbbbbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffccccffffffffffffffff
ffffffbcccdddddbdddddd1bbbbdddddbbbbbdddddbbdddd1bbbbbdddd1bbdddddbbbbbdddddbbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccccffcccccfffffffffffffff
ffffffbcccdddddbddddddd1bbbdddddb1d11dddd1bbdddddbd111dddd1bbdddddb1d11dddd1bbbbbbbdddddbbbbccccbcccccccccccccccccccccccccccccccccccccccccfffccccccfffffffffffff
ffffffbcccdddddbbddddddd1bbdddddbdddddddd1bbdddd1bdddddddddbbdddddbdddddddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
ffffffbcccdddddbbbdddddddbbdddddbdddddddddbbdddddbdddddddd1bbdddddbdddddddddbbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
ffffffbcccdddddbbbbddddddbbdddddbdddddddddbbdddddbdddddddddbbdddddbdddddddddbbbbbbbdddddbbbcccccbccccccccccccccccccccccccccccccccccccccccccccccccccccffff1ffffff
ffffffbcccdddddcccccdddd1cbdddddcdddddddddccdddd1cdddddddd1ccdddddcdddddddddcccccccdddd1ccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcff1fffff
ff1f1f1bcccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccbcffff11f
ffffff11bcccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccbfffffff
fffffffffbcccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbffffff
ffffffffccbbbbbbbbbbbbbbcccd1ddd11d1111111cc1d111cccccd1d11ccd1dd11d11111111cc1d111ccccc1d111bc1d111cc1d111ccccc1d111ccd1dd11d11111111cc1d111cccccccccccccbfffff
ffffffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbdddd1bbdddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbbbbcccccbfffff
ff11ffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbb1dddd1bbdddd1bbdddd1bbbb1dddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
ff11ffffcccccccccccccccbcccdddddddddddddddbbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbddddd1bbdddd1bbdddd1bbbbddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
fffffffffccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbb1ddddd1bbdddd1bbdddd1bbb1ddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfccff
fffffffccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbddddd1bbbdddd1bbdddd1bbbddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
ffffcccccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbdddddd1bbbdddd1bbdddd1bbdddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
fffccccccccccccccccccccbcccdddddbd1dd11d11bbdddd1bbbbbdddd1bbdddddb1d11dddddbbdddd1bbddddd1bbbbdddd1bbdddd1bbddddd1bbbbdddddb1d11dddd1bbdddd1bbbbbbbbbccccbccccc
ffffcccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddd1bbdddd1bdddddd1bbbbdddd1bbdddd1bdddddd1bbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
fffccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbbddddddbbbbbdddd1bbddddbbddddddbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbdddddd1bbbbbdddd1bbddddbdddddd1bbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbbbbbbbbbbbbdddbbddddddbbbbbbdddddbbdddbbddddddbbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddddbbbbbdddd1bbdddddbd1d111bbbbbdddbdddddddbbbbbbdddd1bbdddbdddddddbbbbbbdddddbbbbbdddd1bbdddddbbbbbbbbbccccbccccc
fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbdddddd1bbbbddbbddddddbbbbbbbdddd1bbddbbddddddbbbbbbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbccccc
fccccccccccccccccccccccbccc1dd11d1111dddddbbdddd1bdd11dddd1bbdddddbddddddd1bbbddbdddddddbbbbbbbdddddbbddbdddddddbbbbbbbdddddbbbbbdddddbbdddd1bdd1d11111cccbccccc
fccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddd1bbdddddbbddddddd1bbbbbddddddbbbbbbbbdddddbbbbbddddddbbbbbbbbdddddbbbbbdddddbbdddddbdddddddd1cccbccccc
cccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddddbbdddddbbbdddddddbbbbdddddddbbbbbbbbdddd1bbbbdddddddbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1cccbccccc
cccccccccccccccccccccccbcccdddddddddddddddbbdddd1bdddddddddbbdddddbbbbddddddbbbbddddddbbbbbbbbbdddddbbbbddddddbbbbbbbbbdddddbbbbbdddddbbdddd1bdddddddddcccbccccc
cccccccccccccccccccccccbcccdddddddddddddd1ccdddddcdddddddd1ccdddddcccccdddd1ccccddddddcccccccccdddddccccddddddcccccccccdddddcccccdddd1ccdddddcdddddddd1cccbccccc
ccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccc
cccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccc
ccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccc
cccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccc
ccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccbbcbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbccccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbcccccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccccccccccccccc
ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbcccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbcccbcccccccccccccccccccccccc
cccccccccccccccccccccccccccccccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcccbbbbbbbcccccccccccccccccccccccc
cccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbccccccccccccccccccccccccc
ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccc
ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbccccccccccccccccccccccccc
ccccccccccccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc
ccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccc
cccccccccccccccccccccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbcccccccccccccccccccccc
cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbccccccccccccccccccc
cccccccccccccccccccccccbccbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
ccccccccccccccccccccccbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
ccccccccccccccccccccbbbcbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccc
cccccccccccccccccccccbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccccccccc
cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
cccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
cccccccccccccccccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccc
cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccc
cccccccccccccccbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
cccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
cccccccccccccccccbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbcccccccccccccc
cccccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbccccccccccccc
cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
cccccccccccccbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
cccccccccccccccbbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccc
ccccccccccccccbbbbcbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc
cccccccccccccbbbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccc
cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
