enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const robotdrex = SpriteKind.create()
    export const enemy1 = SpriteKind.create()
    export const heart = SpriteKind.create()
    export const Boss1 = SpriteKind.create()
    export const bomb = SpriteKind.create()
    export const Loot = SpriteKind.create()
}
namespace StatusBarKind {
    export const Boost = StatusBarKind.create()
}
function Healthbar1 () {
    Healthbar = statusbars.create(20, 4, StatusBarKind.Health)
    Healthbar.value = 100
    Healthbar.setLabel("HP")
    Healthbar.positionDirection(CollisionDirection.Top)
    Healthbar.setBarSize(50, 5)
    RobotBoost()
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Loot, function (sprite, otherSprite) {
    if (b == 0) {
        b += 1
        Player1.sayText("I got a Boost upgrade.")
        Chest1.setImage(img`
            . . f f c . . . . c c f . . . . 
            . c b 3 3 c . . f 3 3 c f c . . 
            f b 3 c f 3 c f b c c b 3 b c . 
            f b c c f f c b b c c b c 3 c . 
            f 3 b f f f c b c c b c c 3 f . 
            f 3 b f f f f c c c c c c b b f 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c c 3 c 
            f 3 b f f f f c c c c c c c 3 c 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c b b f 
            f 3 b f f f c b c c b c c 3 f . 
            f b c c f f c b b c c b c 3 c . 
            f b 3 c f 3 c f b c c b 3 b c . 
            . c b 3 3 c . . f 3 3 c f c . . 
            . . f f c . . . . c c f . . . . 
            `)
        sprites.destroy(blast, effects.warmRadial, 500)
        Gas.max += 25
    }
})
statusbars.onZero(StatusBarKind.Boost, function (status) {
    Player1.sayText("Im all out of boost", 2000, false)
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile11`, function (sprite, location) {
    sprites.destroy(blast, effects.fire, 100)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (a >= 1) {
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight))) {
            blast = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . 5 9 9 9 9 9 9 9 . . . 
                . . . . 5 5 5 1 1 1 1 1 1 9 . . 
                . . . . 5 5 5 1 1 1 1 1 1 9 . . 
                . . . . . 5 9 9 9 9 9 9 9 . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Projectile)
            blast.setVelocity(200, 10)
            blast.setPosition(Player1.x + 6, Player1.y)
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff..ff..
                ....ccffffff.fb...
                ..fcbfbfcbcc.cb...
                .fbbbfbfbcbbcbbc..
                .f..cfbfbbbbcfff..
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc.ff.
                ......cfcfff..fb..
                ....ccffffff..cb..
                ..fcbfbfcbccccbbc.
                .fbbbfbfbcbbbcfff.
                .f..cfbfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff..ff..
                ....ccffffff.fb...
                ..fcbfbfcbcc.cb...
                .fbbbfbfbcbbcbbc..
                .f..cfbfbbbbcfff..
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `],
            50,
            false
            )
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft))) {
            blast = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . 9 9 9 9 9 9 9 5 . . . . . 
                . . 9 1 1 1 1 1 1 5 5 5 . . . . 
                . . 9 1 1 1 1 1 1 5 5 5 . . . . 
                . . . 9 9 9 9 9 9 9 5 . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Projectile)
            blast.setVelocity(-200, 10)
            blast.setPosition(Player1.x - 6, Player1.y)
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ..ff..fffcfc......
                ...bf.ffffffcc....
                ...bc.ccbcfbfbcf..
                ..cbbcbbcbfbfbbbf.
                ..fffcbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                .ff.cfcffffff.....
                ..bf..fffcfc......
                ..bc..ffffffcc....
                .cbbccccbcfbfbcf..
                .fffcbbbcbfbfbbbf.
                ......bbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ..ff..fffcfc......
                ...bf.ffffffcc....
                ...bc.ccbcfbfbcf..
                ..cbbcbbcbfbfbbbf.
                ..fffcbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `],
            50,
            false
            )
        }
    }
})
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile14`, function (sprite, location) {
    sprites.destroy(blast, effects.fire, 100)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (a >= 1) {
        if (Player1.isHittingTile(CollisionDirection.Bottom) && Gas.value > 50) {
            Player1.vy = -200
        } else if (Player1.isHittingTile(CollisionDirection.Bottom) && (Gas.value > 0 && Gas.value < 50)) {
            Player1.vy = -100
        }
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f11cfbfbcbbfc11f.
                .5995.bfbbbb.5995.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f11cfbfbcbbfc11f.
                .5995.bfbbbb.5995.
                .9999.fccccf.9999.
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f..cfbfbcbbfc..f.
                ......bfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f..cfbfbcbbfc..f.
                ......bfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f111f111f....
                ......999.999.....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `],
            100,
            false
            )
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f11cfbbcbfbfc11f.
                .5995.bbbbfb.5995.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f11cfbbcbfbfc11f.
                .5995.bbbbfb.5995.
                .9999.fccccf.9999.
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f..cfbbcbfbfc..f.
                ......bbbbfb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f..cfbbcbfbfc..f.
                ......bbbbfb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f111f111f.....
                .....999.999......
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `],
            100,
            false
            )
        }
    }
})
function Scence () {
	
}
scene.onOverlapTile(SpriteKind.Projectile, assets.tile`myTile4`, function (sprite, location) {
    sprites.destroy(blast, effects.fire, 100)
})
function Newgame () {
    info.setScore(0)
    a += 5
    tiles.setCurrentTilemap(tilemap`level3`)
    Healthbar1()
    Animation()
    Chest()
    spriteplayer()
}
function Animation () {
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ....ccfffcfccc....
        ..fcbffffffffbcf..
        .fbbbfccbcfbfbbbf.
        .f..cfbbcbfbfc..f.
        ......bbbbfb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    500,
    characterAnimations.rule(Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ....cccfcfffcc....
        ..fcbffffffffbcf..
        .fbbbfbfcbccfbbbf.
        .f..cfbfbcbbfc..f.
        ......bfbbbb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `],
    500,
    characterAnimations.rule(Predicate.FacingRight, Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ....ccfffcfccc....
        ..fcbffffffffbcf..
        .fbbbfccbcfbfbbbf.
        .f..cfbbcbfbfc..f.
        ......bbbbfb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    500,
    characterAnimations.rule(Predicate.FacingLeft, Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        ....dcbbbccc......
        ...f2dcbccccc.....
        ...bcccccccbf.....
        ...cbbbcbbfbc.....
        ...c99bb99fcf.....
        ...cbbcbbcfcf.....
        ...cfcffffff......
        ...ccfffcfccc.....
        .fcbffffffffbcf...
        fbbbfccbcfbfbbbf..
        f..cfbbcbfbfc..f..
        ....fbbbbfb.......
        .....cccccf.......
        .....fffffff......
        .....ff...ff......
        ....fcf..fcf......
        ...fcbb.fbcbf.....
        `,img`
        ..................
        ....dcbbbccc......
        ...f2dcbccccc.....
        ...bcccccccbf.....
        ...cbbbcbbfbc.....
        ...c99bb99fcf.....
        ...cbbcbbcfcf.....
        ...cfcffffff......
        .....fffcfc.......
        ...ccffffffcc.....
        .fcbfccbcfbfbcf...
        fbbbfbbcbfbfbbbf..
        f..cfbbbbfbfc..f..
        ....fcccccf.......
        ....fffffff.......
        .....ff..ff.......
        ....fcf.fcf.......
        ...fcbbfbcbf......
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        .....fcccccf......
        .....fffffff......
        .....ff...ff......
        ....fcf..fcf......
        ...fcbb.fbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    100,
    characterAnimations.rule(Predicate.FacingLeft, Predicate.MovingLeft, Predicate.HittingWallDown)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        ......cccbbbcd....
        .....cccccbcd2f...
        .....fbcccccccb...
        .....cbfbbcbbbc...
        .....fcf99bb99c...
        .....fcfcbbcbbc...
        ......ffffffcfc...
        .....cccfcfffcc...
        ...fcbffffffffbcf.
        ..fbbbfbfcbccfbbbf
        ..f..cfbfbcbbfc..f
        .......bfbbbbf....
        .......fccccc.....
        ......fffffff.....
        ......ff...ff.....
        ......fcf..fcf....
        .....fbcbf.bbcf...
        `,img`
        ..................
        ......cccbbbcd....
        .....cccccbcd2f...
        .....fbcccccccb...
        .....cbfbbcbbbc...
        .....fcf99bb99c...
        .....fcfcbbcbbc...
        ......ffffffcfc...
        .......cfcfff.....
        .....ccffffffcc...
        ...fcbfbfcbccfbcf.
        ..fbbbfbfbcbbfbbbf
        ..f..cfbfbbbbfc..f
        .......fcccccf....
        .......fffffff....
        .......ff..ff.....
        .......fcf.fcf....
        ......fbcbfbbcf...
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fcccccf.....
        ......fffffff.....
        ......ff...ff.....
        ......fcf..fcf....
        .....fbcbf.bbcf...
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `],
    100,
    characterAnimations.rule(Predicate.FacingRight, Predicate.MovingRight, Predicate.HittingWallDown)
    )
}
function Startmenu () {
    myMenu = miniMenu.createMenu(
    miniMenu.createMenuItem("New Game"),
    miniMenu.createMenuItem("Controls"),
    miniMenu.createMenuItem("Credits")
    )
    myMenu.setStyleProperty(miniMenu.StyleKind.Default, miniMenu.StyleProperty.Background, 11)
    myMenu.setStyleProperty(miniMenu.StyleKind.Selected, miniMenu.StyleProperty.Background, 12)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.Width, 120)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.Height, 42)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.ScrollIndicatorColor, 1)
    myMenu.setFrame(img`
        ....bbbbbbbbbb......
        ...bccccccccccb.....
        ..bccccccccccccb....
        .bccccccccccccccb...
        bcccccbbbbbbcccccb..
        bccccbbbbbbbbccccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bccccbbbbbbbbccccb..
        bcccccbbbbbbcccccb..
        .bccccccccccccccb...
        ..bccccccccccccb....
        ...bccccccccccb.....
        ....bbbbbbbbbb......
        ....................
        ....................
        `)
    myMenu.setPosition(86, 95)
    myMenu.onButtonPressed(controller.A, function (selection, selectedIndex) {
        myMenu.close()
        if (selection == "New Game") {
            Newgame()
        } else if (selection == "Controls") {
            game.showLongText("USE WASD TO MOVE, B TO SHOOT, AND A TO JUMP", DialogLayout.Bottom)
            Startmenu()
        } else if (selection == "Credits") {
        	
        }
    })
    myMenu.moveSelection(miniMenu.MoveDirection.Left)
}
function Chest () {
    Chest1 = sprites.create(img`
        . . . . . . . c f f . . . . . . 
        . . . . . . c d c b c . . . . . 
        . . . . . c 3 d c 3 b f . . . . 
        . . . . . c 3 b c c b f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . c b 3 3 d c 3 f . . . . 
        . . . . c 3 3 b c b b f . . . . 
        . . . . c 3 3 3 d c 3 f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . c 3 3 b c b b f . . . . 
        . . . . c b 3 3 d c 3 f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . . c 3 b c c b f . . . . 
        . . . . . c 3 d c 3 b f . . . . 
        . . . . . . c d c b c . . . . . 
        . . . . . . . c f f . . . . . . 
        `, SpriteKind.Loot)
    tiles.placeOnTile(Chest1, tiles.getTileLocation(19, 15))
    Chest2 = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    tiles.placeOnTile(Chest2, tiles.getTileLocation(52, 10))
}
function spriteplayer () {
    Player1 = sprites.create(img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `, SpriteKind.robotdrex)
    controller.moveSprite(Player1, 50, 0)
    scene.cameraFollowSprite(Player1)
    Player1.setPosition(6, 111)
    Player1.sayText("I must find a way out of here", 5000, false)
    tiles.placeOnTile(Player1, tiles.getTileLocation(3, 11))
    Player1.ay = 600
}
function RobotBoost () {
    Gas = statusbars.create(20, 4, StatusBarKind.Boost)
    Gas.value = 100
    Gas.setColor(9, 2)
    Gas.setLabel("Boost")
    Gas.positionDirection(CollisionDirection.Bottom)
    Gas.setBarSize(20, 4)
}
controller.A.onEvent(ControllerButtonEvent.Repeated, function () {
    if (a >= 1 && b >= 1) {
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight)) && Gas.value > 0) {
            Player1.vy = -200
            if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.MovingUp, Predicate.FacingRight))) {
                animation.runImageAnimation(
                Player1,
                [img`
                    .....cccbbbcd.......
                    ....cccccbcd2f......
                    ....fbcccccccb......
                    ....cbfbbcbbbc......
                    ....fcf99bb99c......
                    ....fcfcbbcbbc......
                    .....ffffffcfc......
                    ....cccfcfffcc......
                    ..fcbffffffffbcf....
                    .fbbbfbfcbccfbbbf...
                    .f11cfbfbcbbfc11f...
                    .5995.bfbbbb.5995...
                    599995fccccf599995..
                    .5995.ffffff.5995...
                    ..55..ff..ff..55....
                    ......fcf.fcf.......
                    .....f515f515f......
                    .....5999.9995......
                    ....59999.99995.....
                    ...599999.999995....
                    `],
                100,
                false
                )
            }
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft)) && Gas.value > 0) {
            Player1.vy = -200
            if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.MovingUp, Predicate.FacingLeft))) {
                animation.runImageAnimation(
                Player1,
                [img`
                    .......dcbbbccc.....
                    ......f2dcbccccc....
                    ......bcccccccbf....
                    ......cbbbcbbfbc....
                    ......c99bb99fcf....
                    ......cbbcbbcfcf....
                    ......cfcffffff.....
                    ......ccfffcfccc....
                    ....fcbffffffffbcf..
                    ...fbbbfccbcfbfbbbf.
                    ...f11cfbbcbfbfc11f.
                    ...5995.bbbbfb.5995.
                    ..599995fccccf599995
                    ...5995.ffffff.5995.
                    ....55..ff..ff..55..
                    .......fcf.fcf......
                    ......f515f515f.....
                    ......5999.9995.....
                    .....59999.99995....
                    ....599999.999995...
                    `],
                100,
                false
                )
            }
        }
    }
})
scene.onHitWall(SpriteKind.Projectile, function (sprite, location) {
    sprites.destroy(blast, effects.fire, 100)
})
let Chest2: Sprite = null
let myMenu: miniMenu.MenuSprite = null
let Gas: StatusBarSprite = null
let blast: Sprite = null
let Chest1: Sprite = null
let Player1: Sprite = null
let Healthbar: StatusBarSprite = null
let b = 0
let a = 0
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffcffffffffffffffffffffffffffdddddfffffffffffffddfffffdfdfffffffffffffffffffffffffffffffffffffffffffffffcffcffffffffffffffffffffffffffffff
    fffcfffffffffffffffffcfffffffffffffbffbffffffffffffdddddfffffffffffffddfffffffff11fffffffffffffffffff1fffffffff11fffffffffffffffffffffffffffffffcfcfffffffffffff
    fffffcffffffffffffffffffffffffffffffffffffffffffffffdddff11fffff11ffffffffffffff11fff11fffffffffffffffff1ffffff11fffffbbfffffffffffffffffffffffffffffcfcffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffff11fffffffffffffffffff11fffff1ff1ffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
    ffffbffbfffbfffbfffffffffffffffffffffffffffffffdfdfffffffffffffffffffccfffffccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffbfbfffffffffff
    ffffffffffffbfbffffffffffdfffffffffffffffffffffffffffffffffffffffffffccccccfccccccccfffffcccccffffffffccfffffffffff1ffffffbbfffbffffffffffbbfffffffffffffcfcffff
    fffffffffffffffffffffffffffdffffdfffffffffffdffffffff1ff1fffffffffffcccccccffccccccccccccccccccfffcccccccfffcfffffffff1fffbbfffbfffbffffffffffffbfbfffffffffffff
    ffffffffffffffffffffffdffdffffdffffff11ffffffffffffffffffffffffffffccccccccfccccccccccccccccccccffcccccccfffccccffffffffffffffffffbffffffffffffffffffbfbffffffff
    fffffffffffffffffffffffffffffffffffff11ffffdffffffccfffffffcccfffccccccccccccccccccccccccccccccccffcccccccccccccffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffccccccccffcccccffccccccccccccccccccccccccccccccccfcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff1f1fffffffffffffffffccfffcccccccccccccccfccccccccccccccccccccccccccccccccfcccccccccccccccfffffffffffffffffffffffffff1ffffffffffffffffffc
    ffffffffddfffffffffffffffffffff11ffffffffffccffffccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccfffff1ffff1ffffffffffffff11fffffffbfbffffffffc
    ffffffffddffffdfdfffffffffffff1111ffffcccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff1ff1ffffffff11ffffffffffffffffffffffffff
    fffbbfffffffffffffffffffffffff1111ffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffff11ffffffffff11ffffffffffffff
    fffbbfffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccfffffffffffffffffffffffffffff1fffffffffffffff
    fffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccffffffccfffff1ffffffffffffffffffffffffbbfffff
    ffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccfffccccffffff1fffffff1ffffffffffffffbbfffff
    fffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccfffcccccfffffffffffffffffffffffdfffffffffff
    ffffffbcccd1dd11d11111111ccdd1d11111cd1d11cc1d111cd1dd11d11ccdd1d11111cd1d11ccd1dd11dd1111111cccbcccccccccccccccccccccfffcccccccffffffffffffff1ffffffffdffffffff
    ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddd1cccbccccccccccccccccccccccffcccccccccccffcfffffffffffffffffffffffff
    ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbccccccccccccccccccccccffccccccccccccfccffffffffffffffffffffffff
    ffffffbcccdddddddddddddd1bbdddddddddbdddd1bbdddd1bdddddddd1bbdddddddddbdddd1bbdddddddddddddd1cccbccccccccccccccccccccccccfccccccccccccccffffffffffffffffffffffff
    cfffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbcccccccccccccccccccccccccccccccccccccccccfff11fffffffffffffffff
    ffcfffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbbbbbbbbbbccccbcccccccccccccccccccccccccccccccccccccccccccf11fffffffffffffffff
    ffffffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbb1d111bbbbccccbcccccccccccccccccccccccccccccccccccccccccccffffffffff111fffffff
    fffff1bcccdddddb1d11dddddbbdddddbbbbbdddd1bbdddd1b1d11dddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccffffffffff11111ffffff
    ffffffbcccdddddbdddddddd1bbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffff
    ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffbf
    ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccffffffcfffffff111fffffff
    ffffffbcccdddddbbbbbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccfffffcccffffffffffffffbf
    ffffffbcccdddddbd1d111bbbbbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffccccffffffffffffffff
    ffffffbcccdddddbdddddd1bbbbdddddbbbbbdddddbbdddd1bbbbbdddd1bbdddddbbbbbdddddbbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccccffcccccfffffffffffffff
    ffffffbcccdddddbddddddd1bbbdddddb1d11dddd1bbdddddbd111dddd1bbdddddb1d11dddd1bbbbbbbdddddbbbbccccbcccccccccccccccccccccccccccccccccccccccccfffccccccfffffffffffff
    ffffffbcccdddddbbddddddd1bbdddddbdddddddd1bbdddd1bdddddddddbbdddddbdddddddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
    ffffffbcccdddddbbbdddddddbbdddddbdddddddddbbdddddbdddddddd1bbdddddbdddddddddbbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
    ffffffbcccdddddbbbbddddddbbdddddbdddddddddbbdddddbdddddddddbbdddddbdddddddddbbbbbbbdddddbbbcccccbccccccccccccccccccccccccccccccccccccccccccccccccccccffff1ffffff
    ffffffbcccdddddcccccdddd1cbdddddcdddddddddccdddd1cdddddddd1ccdddddcdddddddddcccccccdddd1ccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcff1fffff
    ff1f1f1bcccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccbcffff11f
    ffffff11bcccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccbfffffff
    fffffffffbcccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbffffff
    ffffffffccbbbbbbbbbbbbbbcccd1ddd11d1111111cc1d111cccccd1d11ccd1dd11d11111111cc1d111ccccc1d111bc1d111cc1d111ccccc1d111ccd1dd11d11111111cc1d111cccccccccccccbfffff
    ffffffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbdddd1bbdddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbbbbcccccbfffff
    ff11ffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbb1dddd1bbdddd1bbdddd1bbbb1dddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
    ff11ffffcccccccccccccccbcccdddddddddddddddbbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbddddd1bbdddd1bbdddd1bbbbddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
    fffffffffccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbb1ddddd1bbdddd1bbdddd1bbb1ddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfccff
    fffffffccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbddddd1bbbdddd1bbdddd1bbbddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
    ffffcccccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbdddddd1bbbdddd1bbdddd1bbdddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
    fffccccccccccccccccccccbcccdddddbd1dd11d11bbdddd1bbbbbdddd1bbdddddb1d11dddddbbdddd1bbddddd1bbbbdddd1bbdddd1bbddddd1bbbbdddddb1d11dddd1bbdddd1bbbbbbbbbccccbccccc
    ffffcccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddd1bbdddd1bdddddd1bbbbdddd1bbdddd1bdddddd1bbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    fffccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbbddddddbbbbbdddd1bbddddbbddddddbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbdddddd1bbbbbdddd1bbddddbdddddd1bbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbbbbbbbbbbbbdddbbddddddbbbbbbdddddbbdddbbddddddbbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddddbbbbbdddd1bbdddddbd1d111bbbbbdddbdddddddbbbbbbdddd1bbdddbdddddddbbbbbbdddddbbbbbdddd1bbdddddbbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbdddddd1bbbbddbbddddddbbbbbbbdddd1bbddbbddddddbbbbbbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccc1dd11d1111dddddbbdddd1bdd11dddd1bbdddddbddddddd1bbbddbdddddddbbbbbbbdddddbbddbdddddddbbbbbbbdddddbbbbbdddddbbdddd1bdd1d11111cccbccccc
    fccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddd1bbdddddbbddddddd1bbbbbddddddbbbbbbbbdddddbbbbbddddddbbbbbbbbdddddbbbbbdddddbbdddddbdddddddd1cccbccccc
    cccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddddbbdddddbbbdddddddbbbbdddddddbbbbbbbbdddd1bbbbdddddddbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1cccbccccc
    cccccccccccccccccccccccbcccdddddddddddddddbbdddd1bdddddddddbbdddddbbbbddddddbbbbddddddbbbbbbbbbdddddbbbbddddddbbbbbbbbbdddddbbbbbdddddbbdddd1bdddddddddcccbccccc
    cccccccccccccccccccccccbcccdddddddddddddd1ccdddddcdddddddd1ccdddddcccccdddd1ccccddddddcccccccccdddddccccddddddcccccccccdddddcccccdddd1ccdddddcdddddddd1cccbccccc
    ccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccc
    cccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccc
    ccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccc
    cccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbcbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbcccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbcccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbcccbcccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcccbbbbbbbcccccccccccccccccccccccc
    cccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccc
    cccccccccccccccccccccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbcccccccccccccccccccccc
    cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbccccccccccccccccccc
    cccccccccccccccccccccccbccbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    ccccccccccccccccccccccbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
    ccccccccccccccccccccbbbcbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
    ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccc
    cccccccccccccccbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbcccccccccccccc
    cccccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    cccccccccccccbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
    cccccccccccccccbbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccc
    ccccccccccccccbbbbcbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc
    cccccccccccccbbbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    `)
color.startFade(color.Black, color.originalPalette)
a = 0
b = 0
Startmenu()
game.onUpdate(function () {
    if (a >= 1) {
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.MovingUp)) || characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.HittingWallUp))) {
            Gas.value += -5
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.HittingWallDown))) {
            Gas.value += 1
        }
    }
})
