enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const robotdrex = SpriteKind.create()
    export const enemy1 = SpriteKind.create()
    export const heart = SpriteKind.create()
    export const Boss1 = SpriteKind.create()
    export const bomb = SpriteKind.create()
    export const Loot = SpriteKind.create()
}
namespace StatusBarKind {
    export const Gas = StatusBarKind.create()
}
function Chest1 () {
    Chest = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    c3 = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    c4 = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    c5 = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    c6 = sprites.create(img`
        . . . . . . f f c . . . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f 3 c d 3 3 3 c . . . . 
        . . . . f b b c b 3 3 c . . . . 
        . . . . f 3 c d 3 3 b c . . . . 
        . . . . f 3 c d 3 b b c . . . . 
        . . . . f b c c b 3 c . . . . . 
        . . . . f b 3 c d 3 c . . . . . 
        . . . . . c b c d c . . . . . . 
        . . . . . . f f c . . . . . . . 
        `, SpriteKind.Loot)
    chest2 = sprites.create(img`
        . . . . . . . c f f . . . . . . 
        . . . . . . c d c b c . . . . . 
        . . . . . c 3 d c 3 b f . . . . 
        . . . . . c 3 b c c b f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . c b 3 3 d c 3 f . . . . 
        . . . . c 3 3 b c b b f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . c 3 3 3 d c 3 f . . . . 
        . . . . c 3 3 b c b b f . . . . 
        . . . . c b 3 3 d c 3 f . . . . 
        . . . . c b b 3 d c 3 f . . . . 
        . . . . . c 3 b c c b f . . . . 
        . . . . . c 3 d c 3 b f . . . . 
        . . . . . . c d c b c . . . . . 
        . . . . . . . c f f . . . . . . 
        `, SpriteKind.Loot)
    tiles.placeOnTile(Chest, tiles.getTileLocation(19, 15))
    tiles.placeOnTile(chest2, tiles.getTileLocation(51, 10))
    tiles.placeOnTile(c3, tiles.getTileLocation(29, 2))
}
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Loot, function (sprite, otherSprite) {
    if (b == 0) {
        Boost.max += 25
        b += 1
        sprites.destroy(blast, effects.warmRadial, 1000)
        Player1.sayText("I got a boost upgrade")
        game.showLongText("You have unlocked your first boost upgrade! You now have the ability to do a boosted jump by holding A. As you progress through the game you will unlock more Boost upgrades making your jump last longer and higher.", DialogLayout.Bottom)
        Chest.setImage(img`
            . . f f c . . . . c c f . . . . 
            . c b 3 3 c . . f 3 3 c f c . . 
            f b 3 c f 3 c f b c c b 3 b c . 
            f b c c f f c b b c c b c 3 c . 
            f 3 b f f f c b c c b c c 3 f . 
            f 3 b f f f f c c c c c c b b f 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c c 3 c 
            f 3 b f f f f c c c c c c c 3 c 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c b b f 
            f 3 b f f f c b c c b c c 3 f . 
            f b c c f f c b b c c b c 3 c . 
            f b 3 c f 3 c f b c c b 3 b c . 
            . c b 3 3 c . . f 3 3 c f c . . 
            . . f f c . . . . c c f . . . . 
            `)
    } else if (b == 1) {
        b += 1
        Boost.max += 25
        Player1.sayText("I got a boost upgrade")
        sprites.destroy(blast, effects.warmRadial, 1000)
        chest2.setImage(img`
            . . . . f c c . . . . c f f . . 
            . . c f c 3 3 f . . c 3 3 b c . 
            . c b 3 b c c b f c 3 f c 3 b f 
            . c 3 c b c c b b c f f c c b f 
            . f 3 c c b c c b c f f f b 3 f 
            f b b c c c c c c f f f f b 3 f 
            c b b b b c c c c f f f f f b f 
            c 3 c c c c c c c f f f f b 3 f 
            c 3 c c c c c c c f f f f b 3 f 
            c b b b b c c c c f f f f f b f 
            f b b c c c c c c f f f f b 3 f 
            . f 3 c c b c c b c f f f b 3 f 
            . c 3 c b c c b b c f f c c b f 
            . c b 3 b c c b f c 3 f c 3 b f 
            . . c f c 3 3 f . . c 3 3 b c . 
            . . . . f c c . . . . c f f . . 
            `)
    } else if (b == 2) {
        Boost.max += 25
        b += 1
        sprites.destroy(blast, effects.warmRadial, 1000)
        Player1.sayText("I got a boost upgrade")
        c3.setImage(img`
            . . f f c . . . . c c f . . . . 
            . c b 3 3 c . . f 3 3 c f c . . 
            f b 3 c f 3 c f b c c b 3 b c . 
            f b c c f f c b b c c b c 3 c . 
            f 3 b f f f c b c c b c c 3 f . 
            f 3 b f f f f c c c c c c b b f 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c c 3 c 
            f 3 b f f f f c c c c c c c 3 c 
            f b f f f f f c c c c b b b b c 
            f 3 b f f f f c c c c c c b b f 
            f 3 b f f f c b c c b c c 3 f . 
            f b c c f f c b b c c b c 3 c . 
            f b 3 c f 3 c f b c c b 3 b c . 
            . c b 3 3 c . . f 3 3 c f c . . 
            . . f f c . . . . c c f . . . . 
            `)
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (a >= 1) {
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight))) {
            blast = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . 5 9 9 9 9 9 9 9 . . . 
                . . . . 5 5 5 1 1 1 1 1 1 9 . . 
                . . . . 5 5 5 1 1 1 1 1 1 9 . . 
                . . . . . 5 9 9 9 9 9 9 9 . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Projectile)
            blast.setVelocity(200, 10)
            blast.setPosition(Player1.x + 6, Player1.y)
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff..ff..
                ....ccffffff.fb...
                ..fcbfbfcbcc.cb...
                .fbbbfbfbcbbcbbc..
                .f..cfbfbbbbcfff..
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc.ff.
                ......cfcfff..fb..
                ....ccffffff..cb..
                ..fcbfbfcbccccbbc.
                .fbbbfbfbcbbbcfff.
                .f..cfbfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff..ff..
                ....ccffffff.fb...
                ..fcbfbfcbcc.cb...
                .fbbbfbfbcbbcbbc..
                .f..cfbfbbbbcfff..
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `],
            50,
            false
            )
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft))) {
            blast = sprites.create(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . 9 9 9 9 9 9 9 5 . . . . . 
                . . 9 1 1 1 1 1 1 5 5 5 . . . . 
                . . 9 1 1 1 1 1 1 5 5 5 . . . . 
                . . . 9 9 9 9 9 9 9 5 . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Projectile)
            blast.setVelocity(-200, 10)
            blast.setPosition(Player1.x - 6, Player1.y)
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ..ff..fffcfc......
                ...bf.ffffffcc....
                ...bc.ccbcfbfbcf..
                ..cbbcbbcbfbfbbbf.
                ..fffcbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                .ff.cfcffffff.....
                ..bf..fffcfc......
                ..bc..ffffffcc....
                .cbbccccbcfbfbcf..
                .fffcbbbcbfbfbbbf.
                ......bbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ..ff..fffcfc......
                ...bf.ffffffcc....
                ...bc.ccbcfbfbcf..
                ..cbbcbbcbfbfbbbf.
                ..fffcbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `],
            50,
            false
            )
        }
    }
})
function Player1p () {
    Player1 = sprites.create(img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `, SpriteKind.robotdrex)
    controller.moveSprite(Player1, 50, 0)
    scene.cameraFollowSprite(Player1)
    Player1.sayText("I must find a way out of here", 5000, false)
    tiles.placeOnTile(Player1, tiles.getTileLocation(cc, cr))
    Player1.ay = 600
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (a >= 1) {
        if (Player1.isHittingTile(CollisionDirection.Bottom) && Boost.value > 50) {
            Player1.vy = -200
        } else if (Player1.isHittingTile(CollisionDirection.Bottom) && (Boost.value < 50 && Boost.value > 25)) {
            Player1.vy = -150
        } else if (Player1.isHittingTile(CollisionDirection.Bottom) && (Boost.value < 25 && Boost.value > 0)) {
            Player1.vy = -100
        }
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f11cfbfbcbbfc11f.
                .5995.bfbbbb.5995.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f11cfbfbcbbfc11f.
                .5995.bfbbbb.5995.
                .9999.fccccf.9999.
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f..cfbfbcbbfc..f.
                ......bfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f515f515f....
                .....599959995....
                `,img`
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ....cccfcfffcc....
                ..fcbffffffffbcf..
                .fbbbfbfcbccfbbbf.
                .f..cfbfbcbbfc..f.
                ......bfbbbb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....f111f111f....
                ......999.999.....
                `,img`
                ..................
                .....cccbbbcd.....
                ....cccccbcd2f....
                ....fbcccccccb....
                ....cbfbbcbbbc....
                ....fcf99bb99c....
                ....fcfcbbcbbc....
                .....ffffffcfc....
                ......cfcfff......
                ....ccffffffcc....
                ..fcbfbfcbccfbcf..
                .fbbbfbfbcbbfbbbf.
                .f..cfbfbbbbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                ......fcf.fcf.....
                .....fbcbfbbcf....
                `],
            100,
            false
            )
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f11cfbbcbfbfc11f.
                .5995.bbbbfb.5995.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f11cfbbcbfbfc11f.
                .5995.bbbbfb.5995.
                .9999.fccccf.9999.
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f..cfbbcbfbfc..f.
                ......bbbbfb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f515f515f.....
                ....599959995.....
                `,img`
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ....ccfffcfccc....
                ..fcbffffffffbcf..
                .fbbbfccbcfbfbbbf.
                .f..cfbbcbfbfc..f.
                ......bbbbfb......
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....f111f111f.....
                .....999.999......
                `,img`
                ..................
                .....dcbbbccc.....
                ....f2dcbccccc....
                ....bcccccccbf....
                ....cbbbcbbfbc....
                ....c99bb99fcf....
                ....cbbcbbcfcf....
                ....cfcffffff.....
                ......fffcfc......
                ....ccffffffcc....
                ..fcbfccbcfbfbcf..
                .fbbbfbbcbfbfbbbf.
                .f..cfbbbbfbfc..f.
                ......fccccf......
                ......ffffff......
                ......ff..ff......
                .....fcf.fcf......
                ....fcbbfbcbf.....
                `],
            100,
            false
            )
        }
    }
})
function Newgame () {
    a += 5
    tiles.setCurrentTilemap(tilemap`level3`)
    Player1p()
    Health1()
    boostbargas()
    Animation()
    Chest1()
    Enemy1()
}
function Health1 () {
    Healthbar = statusbars.create(20, 4, StatusBarKind.Health)
    Healthbar.value = 100
    Healthbar.setLabel("HP")
    Healthbar.positionDirection(CollisionDirection.Top)
    Healthbar.setBarSize(50, 5)
}
function boostbargas () {
    Boost = statusbars.create(20, 4, StatusBarKind.Gas)
    Boost.setLabel("Boost")
    Boost.value = 100
    Boost.setColor(9, 2)
    Boost.positionDirection(CollisionDirection.Bottom)
}
function Enemy1 () {
    Chest_Guard = sprites.create(img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c22bb22fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `, SpriteKind.Enemy)
    tiles.placeOnTile(Chest_Guard, tiles.getTileLocation(22, 15))
    list = [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c22bb22fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `, img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c22bb22fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `, img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c22bb22fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `]
}
function Animation () {
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ....ccfffcfccc....
        ..fcbffffffffbcf..
        .fbbbfccbcfbfbbbf.
        .f..cfbbcbfbfc..f.
        ......bbbbfb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    500,
    characterAnimations.rule(Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ....cccfcfffcc....
        ..fcbffffffffbcf..
        .fbbbfbfcbccfbbbf.
        .f..cfbfbcbbfc..f.
        ......bfbbbb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `],
    500,
    characterAnimations.rule(Predicate.FacingRight, Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ....ccfffcfccc....
        ..fcbffffffffbcf..
        .fbbbfccbcfbfbbbf.
        .f..cfbbcbfbfc..f.
        ......bbbbfb......
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    500,
    characterAnimations.rule(Predicate.FacingLeft, Predicate.NotMoving)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `,img`
        ..................
        ....dcbbbccc......
        ...f2dcbccccc.....
        ...bcccccccbf.....
        ...cbbbcbbfbc.....
        ...c99bb99fcf.....
        ...cbbcbbcfcf.....
        ...cfcffffff......
        ...ccfffcfccc.....
        .fcbffffffffbcf...
        fbbbfccbcfbfbbbf..
        f..cfbbcbfbfc..f..
        ....fbbbbfb.......
        .....cccccf.......
        .....fffffff......
        .....ff...ff......
        ....fcf..fcf......
        ...fcbb.fbcbf.....
        `,img`
        ..................
        ....dcbbbccc......
        ...f2dcbccccc.....
        ...bcccccccbf.....
        ...cbbbcbbfbc.....
        ...c99bb99fcf.....
        ...cbbcbbcfcf.....
        ...cfcffffff......
        .....fffcfc.......
        ...ccffffffcc.....
        .fcbfccbcfbfbcf...
        fbbbfbbcbfbfbbbf..
        f..cfbbbbfbfc..f..
        ....fcccccf.......
        ....fffffff.......
        .....ff..ff.......
        ....fcf.fcf.......
        ...fcbbfbcbf......
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        .....fcccccf......
        .....fffffff......
        .....ff...ff......
        ....fcf..fcf......
        ...fcbb.fbcbf.....
        `,img`
        ..................
        .....dcbbbccc.....
        ....f2dcbccccc....
        ....bcccccccbf....
        ....cbbbcbbfbc....
        ....c99bb99fcf....
        ....cbbcbbcfcf....
        ....cfcffffff.....
        ......fffcfc......
        ....ccffffffcc....
        ..fcbfccbcfbfbcf..
        .fbbbfbbcbfbfbbbf.
        .f..cfbbbbfbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        .....fcf.fcf......
        ....fcbbfbcbf.....
        `],
    100,
    characterAnimations.rule(Predicate.FacingLeft, Predicate.MovingLeft, Predicate.HittingWallDown)
    )
    characterAnimations.loopFrames(
    Player1,
    [img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `,img`
        ..................
        ......cccbbbcd....
        .....cccccbcd2f...
        .....fbcccccccb...
        .....cbfbbcbbbc...
        .....fcf99bb99c...
        .....fcfcbbcbbc...
        ......ffffffcfc...
        .....cccfcfffcc...
        ...fcbffffffffbcf.
        ..fbbbfbfcbccfbbbf
        ..f..cfbfbcbbfc..f
        .......bfbbbbf....
        .......fccccc.....
        ......fffffff.....
        ......ff...ff.....
        ......fcf..fcf....
        .....fbcbf.bbcf...
        `,img`
        ..................
        ......cccbbbcd....
        .....cccccbcd2f...
        .....fbcccccccb...
        .....cbfbbcbbbc...
        .....fcf99bb99c...
        .....fcfcbbcbbc...
        ......ffffffcfc...
        .......cfcfff.....
        .....ccffffffcc...
        ...fcbfbfcbccfbcf.
        ..fbbbfbfbcbbfbbbf
        ..f..cfbfbbbbfc..f
        .......fcccccf....
        .......fffffff....
        .......ff..ff.....
        .......fcf.fcf....
        ......fbcbfbbcf...
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fcccccf.....
        ......fffffff.....
        ......ff...ff.....
        ......fcf..fcf....
        .....fbcbf.bbcf...
        `,img`
        ..................
        .....cccbbbcd.....
        ....cccccbcd2f....
        ....fbcccccccb....
        ....cbfbbcbbbc....
        ....fcf99bb99c....
        ....fcfcbbcbbc....
        .....ffffffcfc....
        ......cfcfff......
        ....ccffffffcc....
        ..fcbfbfcbccfbcf..
        .fbbbfbfbcbbfbbbf.
        .f..cfbfbbbbfc..f.
        ......fccccf......
        ......ffffff......
        ......ff..ff......
        ......fcf.fcf.....
        .....fbcbfbbcf....
        `],
    100,
    characterAnimations.rule(Predicate.FacingRight, Predicate.MovingRight, Predicate.HittingWallDown)
    )
}
function Startmenu () {
    myMenu = miniMenu.createMenu(
    miniMenu.createMenuItem("New Game"),
    miniMenu.createMenuItem("Controls"),
    miniMenu.createMenuItem("Credits")
    )
    myMenu.setStyleProperty(miniMenu.StyleKind.Default, miniMenu.StyleProperty.Background, 11)
    myMenu.setStyleProperty(miniMenu.StyleKind.Selected, miniMenu.StyleProperty.Background, 12)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.Width, 120)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.Height, 42)
    myMenu.setMenuStyleProperty(miniMenu.MenuStyleProperty.ScrollIndicatorColor, 1)
    myMenu.setFrame(img`
        ....bbbbbbbbbb......
        ...bccccccccccb.....
        ..bccccccccccccb....
        .bccccccccccccccb...
        bcccccbbbbbbcccccb..
        bccccbbbbbbbbccccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bcccbbbbbbbbbbcccb..
        bccccbbbbbbbbccccb..
        bcccccbbbbbbcccccb..
        .bccccccccccccccb...
        ..bccccccccccccb....
        ...bccccccccccb.....
        ....bbbbbbbbbb......
        ....................
        ....................
        `)
    myMenu.setPosition(86, 95)
    myMenu.onButtonPressed(controller.A, function (selection, selectedIndex) {
        myMenu.close()
        if (selection == "New Game") {
            Newgame()
        } else if (selection == "Controls") {
            game.showLongText("USE WASD TO MOVE, B TO SHOOT, AND A TO JUMP", DialogLayout.Bottom)
            Startmenu()
        } else if (selection == "Credits") {
        	
        }
    })
    myMenu.moveSelection(miniMenu.MoveDirection.Left)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile8`, function (sprite, location) {
	
})
statusbars.onZero(StatusBarKind.Gas, function (status) {
    Player1.sayText("Im all out of boost", 1000, false)
})
controller.A.onEvent(ControllerButtonEvent.Repeated, function () {
    if (b >= 1 && Boost.value > 25) {
        Player1.vy = -200
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingRight))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ......cccbbbcd......
                .....cccccbcd2f.....
                .....fbcccccccb.....
                .....cbfbbcbbbc.....
                .....fcf99bb99c.....
                .....fcfcbbcbbc.....
                ......ffffffcfc.....
                .......cfcfff.......
                .....ccffffffcc.....
                ...fcbfbfcbccfbcf...
                ..fbbbfbfbcbbfbbbf..
                ..f11cfbfbbbbfc11f..
                ..5995.fccccf.5995..
                .599995ffffff599995.
                .......ff..ff.......
                .......fcf.fcf......
                ......fbcbfbbcf.....
                .....51111.11115....
                ....599999.999995...
                ...5999999.9999995..
                `],
            50,
            false
            )
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.FacingLeft))) {
            animation.runImageAnimation(
            Player1,
            [img`
                ......dcbbbccc......
                .....f2dcbccccc.....
                .....bcccccccbf.....
                .....cbbbcbbfbc.....
                .....c99bb99fcf.....
                .....cbbcbbcfcf.....
                .....cfcffffff......
                .......fffcfc.......
                .....ccffffffcc.....
                ...fcbfccbcfbfbcf...
                ..fbbbfbbcbfbfbbbf..
                ..f11cfbbbbfbfc11f..
                ..5995.fccccf.5995..
                .599995ffffff599995.
                .......ff..ff.......
                ......fcf.fcf.......
                .....fcbbfbcbf......
                ....51111.11115.....
                ...599999.999995....
                ..5999999.9999995...
                `],
            50,
            false
            )
        }
    }
})
scene.onHitWall(SpriteKind.Projectile, function (sprite, location) {
    sprites.destroy(blast, effects.fire, 100)
})
let myMenu: miniMenu.MenuSprite = null
let list: Image[] = []
let Chest_Guard: Sprite = null
let Healthbar: StatusBarSprite = null
let Player1: Sprite = null
let blast: Sprite = null
let Boost: StatusBarSprite = null
let chest2: Sprite = null
let c6: Sprite = null
let c5: Sprite = null
let c4: Sprite = null
let c3: Sprite = null
let Chest: Sprite = null
let b = 0
let a = 0
let cc = 0
let cr = 0
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffcffffffffffffffffffffffffffdddddfffffffffffffddfffffdfdfffffffffffffffffffffffffffffffffffffffffffffffcffcffffffffffffffffffffffffffffff
    fffcfffffffffffffffffcfffffffffffffbffbffffffffffffdddddfffffffffffffddfffffffff11fffffffffffffffffff1fffffffff11fffffffffffffffffffffffffffffffcfcfffffffffffff
    fffffcffffffffffffffffffffffffffffffffffffffffffffffdddff11fffff11ffffffffffffff11fff11fffffffffffffffff1ffffff11fffffbbfffffffffffffffffffffffffffffcfcffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffff11fffff11fffffffffffffffffff11fffff1ff1ffffffffffffffffffffffbbffffffffffffffffffffffffffffffffffffffff
    ffffbffbfffbfffbfffffffffffffffffffffffffffffffdfdfffffffffffffffffffccfffffccccccffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbffffffbfbfffffffffff
    ffffffffffffbfbffffffffffdfffffffffffffffffffffffffffffffffffffffffffccccccfccccccccfffffcccccffffffffccfffffffffff1ffffffbbfffbffffffffffbbfffffffffffffcfcffff
    fffffffffffffffffffffffffffdffffdfffffffffffdffffffff1ff1fffffffffffcccccccffccccccccccccccccccfffcccccccfffcfffffffff1fffbbfffbfffbffffffffffffbfbfffffffffffff
    ffffffffffffffffffffffdffdffffdffffff11ffffffffffffffffffffffffffffccccccccfccccccccccccccccccccffcccccccfffccccffffffffffffffffffbffffffffffffffffffbfbffffffff
    fffffffffffffffffffffffffffffffffffff11ffffdffffffccfffffffcccfffccccccccccccccccccccccccccccccccffcccccccccccccffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffccccccccffcccccffccccccccccccccccccccccccccccccccfcccccccccccccfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffff1f1fffffffffffffffffccfffcccccccccccccccfccccccccccccccccccccccccccccccccfcccccccccccccccfffffffffffffffffffffffffff1ffffffffffffffffffc
    ffffffffddfffffffffffffffffffff11ffffffffffccffffccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccccccfffff1ffff1ffffffffffffff11fffffffbfbffffffffc
    ffffffffddffffdfdfffffffffffff1111ffffcccccccffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccffffff1ff1ffffffff11ffffffffffffffffffffffffff
    fffbbfffffffffffffffffffffffff1111ffcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffffffffff11ffffffffff11ffffffffffffff
    fffbbfffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccfffffffffffffffffffffffffffff1fffffffffffffff
    fffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccffffffccfffff1ffffffffffffffffffffffffbbfffff
    ffffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccfffccccffffff1fffffff1ffffffffffffffbbfffff
    fffffffbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccccccccccccccccfffcccccfffffffffffffffffffffffdfffffffffff
    ffffffbcccd1dd11d11111111ccdd1d11111cd1d11cc1d111cd1dd11d11ccdd1d11111cd1d11ccd1dd11dd1111111cccbcccccccccccccccccccccfffcccccccffffffffffffff1ffffffffdffffffff
    ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddd1cccbccccccccccccccccccccccffcccccccccccffcfffffffffffffffffffffffff
    ffffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbccccccccccccccccccccccffccccccccccccfccffffffffffffffffffffffff
    ffffffbcccdddddddddddddd1bbdddddddddbdddd1bbdddd1bdddddddd1bbdddddddddbdddd1bbdddddddddddddd1cccbccccccccccccccccccccccccfccccccccccccccffffffffffffffffffffffff
    cfffffbcccdddddddddddddd1bbdddddddd1bdddd1bbdddd1bdddddddd1bbdddddddd1bdddd1bbdddddddddddddddcccbcccccccccccccccccccccccccccccccccccccccccfff11fffffffffffffffff
    ffcfffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbbbbbbbbbbccccbcccccccccccccccccccccccccccccccccccccccccccf11fffffffffffffffff
    ffffffbcccdddddbbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbb1d111bbbbccccbcccccccccccccccccccccccccccccccccccccccccccffffffffff111fffffff
    fffff1bcccdddddb1d11dddddbbdddddbbbbbdddd1bbdddd1b1d11dddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccffffffffff11111ffffff
    ffffffbcccdddddbdddddddd1bbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffff
    ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffffff11fff11111ffffbf
    ffffffbcccdddddbdddddddddbbdddddbbbbbdddd1bbdddd1bdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccffffffcfffffff111fffffff
    ffffffbcccdddddbbbbbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccfffffcccffffffffffffffbf
    ffffffbcccdddddbd1d111bbbbbdddddbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccfffccccffffffffffffffff
    ffffffbcccdddddbdddddd1bbbbdddddbbbbbdddddbbdddd1bbbbbdddd1bbdddddbbbbbdddddbbbbbbbdddd1bbbbccccbcccccccccccccccccccccccccccccccccccccccccffcccccfffffffffffffff
    ffffffbcccdddddbddddddd1bbbdddddb1d11dddd1bbdddddbd111dddd1bbdddddb1d11dddd1bbbbbbbdddddbbbbccccbcccccccccccccccccccccccccccccccccccccccccfffccccccfffffffffffff
    ffffffbcccdddddbbddddddd1bbdddddbdddddddd1bbdddd1bdddddddddbbdddddbdddddddd1bbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
    ffffffbcccdddddbbbdddddddbbdddddbdddddddddbbdddddbdddddddd1bbdddddbdddddddddbbbbbbbdddd1bbbbccccbccccccccccccccccccccccccccccccccccccccccccccccccccccfffffffffff
    ffffffbcccdddddbbbbddddddbbdddddbdddddddddbbdddddbdddddddddbbdddddbdddddddddbbbbbbbdddddbbbcccccbccccccccccccccccccccccccccccccccccccccccccccccccccccffff1ffffff
    ffffffbcccdddddcccccdddd1cbdddddcdddddddddccdddd1cdddddddd1ccdddddcdddddddddcccccccdddd1ccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcff1fffff
    ff1f1f1bcccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccbcffff11f
    ffffff11bcccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccbfffffff
    fffffffffbcccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbffffff
    ffffffffccbbbbbbbbbbbbbbcccd1ddd11d1111111cc1d111cccccd1d11ccd1dd11d11111111cc1d111ccccc1d111bc1d111cc1d111ccccc1d111ccd1dd11d11111111cc1d111cccccccccccccbfffff
    ffffffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbdddd1bbdddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbbbbbcccccbfffff
    ff11ffffcccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbb1dddd1bbdddd1bbdddd1bbbb1dddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
    ff11ffffcccccccccccccccbcccdddddddddddddddbbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbbbddddd1bbdddd1bbdddd1bbbbddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfffff
    fffffffffccccccccccccccbcccdddddddddddddd1bbdddd1bbbbbdddd1bbdddddddddddddd1bbdddd1bbb1ddddd1bbdddd1bbdddd1bbb1ddddd1bbdddddddddddddd1bbdddd1bbbbbbbbbccccbfccff
    fffffffccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbbddddd1bbbdddd1bbdddd1bbbddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
    ffffcccccccccccccccccccbcccdddddbbbbbbbbbbbbdddd1bbbbbdddd1bbdddddbbbbbdddd1bbdddd1bbdddddd1bbbdddd1bbdddd1bbdddddd1bbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbcccff
    fffccccccccccccccccccccbcccdddddbd1dd11d11bbdddd1bbbbbdddd1bbdddddb1d11dddddbbdddd1bbddddd1bbbbdddd1bbdddd1bbddddd1bbbbdddddb1d11dddd1bbdddd1bbbbbbbbbccccbccccc
    ffffcccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddd1bbdddd1bdddddd1bbbbdddd1bbdddd1bdddddd1bbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    fffccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbbddddddbbbbbdddd1bbddddbbddddddbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbdddddddddbbddddbdddddd1bbbbbdddd1bbddddbdddddd1bbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    ffcccccccccccccccccccccbcccdddddbdddddddd1bbdddd1bbbbbdddd1bbdddddbbbbbbbbbbbbdddbbddddddbbbbbbdddddbbdddbbddddddbbbbbbdddddbdddddddd1bbdddd1bbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddddbbbbbdddd1bbdddddbd1d111bbbbbdddbdddddddbbbbbbdddd1bbdddbdddddddbbbbbbdddddbbbbbdddd1bbdddddbbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccccbbbbbbbbbdddd1bbdddd1bbbbbdddd1bbdddddbdddddd1bbbbddbbddddddbbbbbbbdddd1bbddbbddddddbbbbbbbdddddbbbbbdddd1bbdddd1bbbbbbbbbccccbccccc
    fccccccccccccccccccccccbccc1dd11d1111dddddbbdddd1bdd11dddd1bbdddddbddddddd1bbbddbdddddddbbbbbbbdddddbbddbdddddddbbbbbbbdddddbbbbbdddddbbdddd1bdd1d11111cccbccccc
    fccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddd1bbdddddbbddddddd1bbbbbddddddbbbbbbbbdddddbbbbbddddddbbbbbbbbdddddbbbbbdddddbbdddddbdddddddd1cccbccccc
    cccccccccccccccccccccccbcccdddddddddddddd1bbdddddbdddddddddbbdddddbbbdddddddbbbbdddddddbbbbbbbbdddd1bbbbdddddddbbbbbbbbdddddbbbbbdddd1bbdddddbdddddddd1cccbccccc
    cccccccccccccccccccccccbcccdddddddddddddddbbdddd1bdddddddddbbdddddbbbbddddddbbbbddddddbbbbbbbbbdddddbbbbddddddbbbbbbbbbdddddbbbbbdddddbbdddd1bdddddddddcccbccccc
    cccccccccccccccccccccccbcccdddddddddddddd1ccdddddcdddddddd1ccdddddcccccdddd1ccccddddddcccccccccdddddccccddddddcccccccccdddddcccccdddd1ccdddddcdddddddd1cccbccccc
    ccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccc
    cccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbccccccc
    ccccccccccccccccccccccccccbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbcccccccc
    cccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbcbbbcccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbcbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbcccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbbcccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbbbbcccbcccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbcccbbbbbbbcccccccccccccccccccccccc
    cccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc
    ccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccc
    cccccccccccccccccccccccbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccbcccccccccccccccccccccc
    cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbccccccccccccccccccc
    cccccccccccccccccccccccbccbbccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccccbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    ccccccccccccccccccccccbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
    ccccccccccccccccccccbbbcbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccccbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbbbbcccccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
    ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccc
    cccccccccccccccbbcbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccc
    cccccccccccccccccbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccbcccccccccccccc
    cccccccccccccccccccbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccbbbbbccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    cccccccccccccbbbcccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccc
    cccccccccccccccbbbbbbcccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcbcccccccccccccc
    ccccccccccccccbbbbcbbbbbccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccc
    ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccc
    ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccc
    cccccccccccccbbbcbcbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccc
    cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccc
    `)
color.startFade(color.Black, color.originalPalette)
cr = 11
cc = 3
a = 0
b = 0
Startmenu()
game.onUpdate(function () {
    if (a > 0) {
        if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.MovingUp)) || characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.HittingWallUp))) {
            Boost.value += -5
        } else if (characterAnimations.matchesRule(Player1, characterAnimations.rule(Predicate.HittingWallDown))) {
            Boost.value += 1
        }
    }
})
game.onUpdate(function () {
    if (a > 1) {
        if (Player1.tileKindAt(TileDirection.Bottom, assets.tile`myTile8`)) {
            if (cr != Player1.tilemapLocation().row && cc != Player1.tilemapLocation().column) {
                game.splash("Checkpoint Reached!")
            }
            cr = Player1.tilemapLocation().row
            cc = Player1.tilemapLocation().column
        }
    }
})
